use chrono::Utc;
use serde_json::json;
use slonq::{JobStatus, PgQueue};
use testcontainers::runners::AsyncRunner;
use testcontainers_modules::postgres::Postgres;
use tokio_postgres::NoTls;

/// The SQL schema required to initialise the `jobs` table and related types.
pub const SCHEMA_SQL: &'static str = r#"
        CREATE TYPE job_status AS ENUM ('pending', 'in_progress', 'done', 'failed');

        CREATE TABLE jobs (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key       TEXT UNIQUE NOT NULL,
            status                job_status  NOT NULL DEFAULT 'pending',
            payload               JSONB       NOT NULL,
            visible_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            attempt_count         INT         NOT NULL DEFAULT 0,
            lease_timeout_seconds INT         NOT NULL DEFAULT 60 CHECK (lease_timeout_seconds > 0),
            lease_id              UUID NULL,
            leased_by             TEXT NULL,
            created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX idx_jobs_visible_status ON jobs (visible_at, status)
        WHERE status IN ('pending', 'in_progress');

        CREATE EXTENSION IF NOT EXISTS pgcrypto;
    "#;

async fn setup_db() -> (PgQueue, testcontainers::ContainerAsync<Postgres>) {
    let node = Postgres::default()
        .start()
        .await
        .expect("Failed to start Postgres");
    let host = node.get_host().await.expect("Failed to get host");
    let port = node
        .get_host_port_ipv4(5432)
        .await
        .expect("Failed to get port");
    let pg_uri = format!("postgres://postgres:postgres@{host}:{port}/postgres");

    let (client, connection) = tokio_postgres::connect(&pg_uri, NoTls)
        .await
        .expect("Failed to connect to Postgres");
    tokio::spawn(async move {
        let _ = connection.await;
    });

    // Create schema
    client
        .batch_execute(SCHEMA_SQL)
        .await
        .expect("Failed to create schema");

    (PgQueue::from_client(client), node)
}

#[tokio::test]
async fn test_enqueue_idempotency() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    let key = "test-key";
    let job1 = queue.enqueue(key, json!({"data": 1}), 10, None).await?;
    assert!(job1.is_some());

    let job1 = job1.unwrap();
    assert_eq!(job1.idempotency_key, key);

    let job2 = queue.enqueue(key, json!({"data": 2}), 10, None).await?;
    assert!(job2.is_none());

    Ok(())
}

#[tokio::test]
async fn test_dequeue_and_ack() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;

    let jobs = queue.dequeue("worker1", 1, 3).await?;
    assert_eq!(jobs.len(), 1);
    let job = &jobs[0];
    let lease = job.lease_key().expect("Should have LeaseKey");

    let acked = queue.ack(lease).await?.expect("Should have Job");
    assert_eq!(acked.status, JobStatus::Done);

    let again = queue.ack(lease).await?;
    assert!(again.is_none());

    Ok(())
}

#[tokio::test]
async fn test_nack_and_retry() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;

    let jobs = queue.dequeue("worker1", 1, 3).await?;
    let lease = jobs[0].lease_key().expect("Should have LeaseKey");

    let nacked = queue.nack(lease, 3, None).await?.expect("Should have Job");
    assert_eq!(nacked.status, JobStatus::Pending);
    assert_eq!(nacked.attempt_count, 1);

    let jobs2 = queue.dequeue("worker2", 1, 3).await?;
    assert_eq!(jobs2.len(), 1);
    assert_eq!(jobs2[0].attempt_count, 2);

    Ok(())
}

#[tokio::test]
async fn test_max_attempts() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;

    // Attempt 1
    let jobs = queue.dequeue("w1", 1, 1).await?;
    let lease = jobs[0].lease_key().expect("Should have LeaseKey");

    // Nack with max_attempts = 1
    let nacked = queue.nack(lease, 1, None).await?.expect("Should have Job");
    assert_eq!(nacked.status, JobStatus::Failed);

    Ok(())
}

#[tokio::test]
async fn test_touch_lease() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;
    let jobs = queue.dequeue("w1", 1, 3).await?;
    let lease = jobs[0].lease_key().expect("Should have LeaseKey");

    let touched = queue.touch(lease, 30).await?.expect("Should have Job");
    assert!(touched.visible_at > jobs[0].visible_at);

    Ok(())
}

#[tokio::test]
async fn test_ack_batch() -> Result<(), Box<dyn std::error::Error>> {
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;
    queue.enqueue("k2", json!(2), 10, None).await?;

    let jobs = queue.dequeue("w1", 10, 3).await?;
    assert_eq!(jobs.len(), 2);

    let leases: Vec<_> = jobs.iter().map(|j| j.lease_key().unwrap()).collect();
    let acked = queue.ack_batch(&leases).await?;
    assert_eq!(acked.len(), 2);
    assert!(acked.iter().all(|j| j.status == JobStatus::Done));

    Ok(())
}

#[tokio::test]
async fn test_nack_with_delay() -> Result<(), Box<dyn std::error::Error>> {
    use std::time::Duration;
    let (queue, _node) = setup_db().await;

    queue.enqueue("k1", json!(1), 10, None).await?;
    let jobs = queue.dequeue("w1", 1, 3).await?;
    let lease = jobs[0].lease_key().unwrap();

    // Nack with a one-hour delay
    let nacked = queue
        .nack(lease, 3, Some(Duration::from_secs(3600)))
        .await?
        .expect("Should have Job");
    assert!(nacked.visible_at > Utc::now() + Duration::from_secs(3500));

    // Should not be able to dequeue immediately
    let jobs2 = queue.dequeue("w2", 1, 3).await.unwrap();
    assert!(jobs2.is_empty());

    Ok(())
}
