import { test, before, after, beforeEach } from 'node:test';
import { strict as assert } from 'node:assert';
import { randomUUID } from 'node:crypto';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { Client } from 'pg';
import { PgQueue, JobStatus } from '../lib';

const SCHEMA_SQL = `
        CREATE TYPE job_status AS ENUM ('pending', 'in_progress', 'done', 'failed');

        CREATE TABLE jobs (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key       TEXT UNIQUE NOT NULL,
            status                job_status  NOT NULL DEFAULT 'pending',
            payload               JSONB       NOT NULL,
            visible_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            attempt_count         INT         NOT NULL DEFAULT 0,
            lease_timeout_seconds INT         NOT NULL DEFAULT 60 CHECK (lease_timeout_seconds > 0),
            lease_id              UUID NULL,
            leased_by             TEXT NULL,
            created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX idx_jobs_visible_status ON jobs (visible_at, status)
        WHERE status IN ('pending', 'in_progress');
`;

let container: StartedPostgreSqlContainer;
let pgUri: string;
let queue: PgQueue;

before(async () => {
  container = await new PostgreSqlContainer('postgres:16-alpine').start();
  pgUri = container.getConnectionUri();
}, { timeout: 120_000 });

after(async () => {
  await container?.stop();
});

beforeEach(async () => {
  const client = new Client({ connectionString: pgUri });
  await client.connect();
  try {
    await client.query('DROP TABLE IF EXISTS jobs');
    await client.query('DROP TYPE  IF EXISTS job_status');
    await client.query(SCHEMA_SQL);
  } finally {
    await client.end();
  }
  queue = await PgQueue.connect(pgUri);
});

test('enqueue is idempotent on idempotency_key', async () => {
  const key = `test-key-${randomUUID()}`;
  const first = await queue.enqueue(key, { data: 1 }, 10);
  assert.ok(first);
  assert.equal(first.idempotencyKey, key);

  const second = await queue.enqueue(key, { data: 2 }, 10);
  assert.equal(second, null);
});

test('dequeue + ack moves job to done; second ack is no-op', async () => {
  const key = `k1-${randomUUID()}`;
  await queue.enqueue(key, 1, 10);

  const jobs = await queue.dequeue('worker1', 1, 3);
  assert.equal(jobs.length, 1);
  const lease = jobs[0]!.leaseKey();
  assert.ok(lease);

  const acked = await queue.ack(lease);
  assert.ok(acked);
  assert.equal(acked.status, JobStatus.Done);

  const again = await queue.ack(lease);
  assert.equal(again, null);
});

test('nack returns job to pending and increments attempt_count', async () => {
  const key = `k1-${randomUUID()}`;
  await queue.enqueue(key, 1, 10);

  const jobs = await queue.dequeue('worker1', 1, 3);
  const lease = jobs[0]!.leaseKey();
  assert.ok(lease);

  const nacked = await queue.nack(lease, 3);
  assert.ok(nacked);
  assert.equal(nacked.status, JobStatus.Pending);
  assert.equal(nacked.attemptCount, 1);

  const jobs2 = await queue.dequeue('worker2', 1, 3);
  assert.equal(jobs2.length, 1);
  assert.equal(jobs2[0]!.attemptCount, 2);
});

test('nack past max_attempts marks job failed', async () => {
  const key = `k1-${randomUUID()}`;
  await queue.enqueue(key, 1, 10);

  const jobs = await queue.dequeue('w1', 1, 1);
  const lease = jobs[0]!.leaseKey();
  assert.ok(lease);

  const nacked = await queue.nack(lease, 1);
  assert.ok(nacked);
  assert.equal(nacked.status, JobStatus.Failed);
});

test('touch extends visible_at', async () => {
  const key = `k1-${randomUUID()}`;
  await queue.enqueue(key, 1, 10);

  const jobs = await queue.dequeue('w1', 1, 3);
  const lease = jobs[0]!.leaseKey();
  assert.ok(lease);

  const touched = await queue.touch(lease, 30);
  assert.ok(touched);

  const before = Date.parse(jobs[0]!.visibleAt);
  const after = Date.parse(touched.visibleAt);
  assert.ok(after > before, `expected ${touched.visibleAt} > ${jobs[0]!.visibleAt}`);
});

test('nack with delay defers visibility', async () => {
  const key = `k1-${randomUUID()}`;
  await queue.enqueue(key, 1, 10);

  const jobs = await queue.dequeue('w1', 1, 3);
  const lease = jobs[0]!.leaseKey();
  assert.ok(lease);

  const nacked = await queue.nack(lease, 3, 3600);
  assert.ok(nacked);

  const visibleAt = Date.parse(nacked.visibleAt);
  const cutoff = Date.now() + 3500 * 1000;
  assert.ok(visibleAt > cutoff, `visibleAt=${nacked.visibleAt} should be > now + 3500s`);

  const jobs2 = await queue.dequeue('w2', 1, 3);
  assert.equal(jobs2.length, 0);
});

test('ackBatch acknowledges all leases', async () => {
  const k1 = `k1-${randomUUID()}`;
  const k2 = `k2-${randomUUID()}`;
  await queue.enqueue(k1, 1, 10);
  await queue.enqueue(k2, 2, 10);

  const jobs = await queue.dequeue('w1', 10, 3);
  assert.equal(jobs.length, 2);

  const leases = jobs.flatMap((j) => {
    const k = j.leaseKey();
    return k ? [k] : [];
  });
  assert.equal(leases.length, 2);

  const acked = await queue.ackBatch(leases);
  assert.equal(acked.length, 2);
  for (const j of acked) {
    assert.equal(j.status, JobStatus.Done);
  }
});

test('ackBatch with empty array is a no-op', async () => {
  const result = await queue.ackBatch([]);
  assert.deepEqual(result, []);
});

test('connect rejects on invalid uri', async () => {
  await assert.rejects(() =>
    PgQueue.connect('postgres://nobody@127.0.0.1:1/__no_such_db__'),
  );
});

test('ack rejects malformed leaseId', async () => {
  await assert.rejects(
    () => queue.ack({ jobId: 1, leaseId: 'not-a-uuid' }),
    /invalid leaseId/,
  );
});

test('payload round-trips nested structures, null and unicode', async () => {
  const payload = {
    nested: { arr: [1, 'two', null, { deep: true }], emoji: '🐘 slonq' },
    n: null,
    bigButSafe: 9_007_199_254_740_991,
  };
  const key = `p-${randomUUID()}`;
  const enq = await queue.enqueue(key, payload, 10);
  assert.deepEqual(enq?.payload, payload);

  const [dequeued] = await queue.dequeue('w1', 1, 3);
  assert.deepEqual(dequeued!.payload, payload);
});

test('undefined payload normalises to JSON null', async () => {
  const key = `u-${randomUUID()}`;
  const enq = await queue.enqueue(key, undefined, 10);
  assert.equal(enq?.payload, null);
});

test('leaseKey returns null after the job is acked', async () => {
  const key = `l-${randomUUID()}`;
  await queue.enqueue(key, {}, 10);

  const [job] = await queue.dequeue('w1', 1, 3);
  const lease = job!.leaseKey();
  assert.ok(lease);

  const acked = await queue.ack(lease);
  assert.ok(acked);
  assert.equal(acked.status, JobStatus.Done);
  assert.equal(acked.leaseKey(), null);
});
