import pytest
import asyncpg
import datetime
import uuid
from testcontainers.postgres import PostgresContainer
from slonq import PgQueue, JobStatus

SCHEMA_SQL = """
        CREATE TYPE job_status AS ENUM ('pending', 'in_progress', 'done', 'failed');

        CREATE TABLE jobs (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key       TEXT UNIQUE NOT NULL,
            status                job_status  NOT NULL DEFAULT 'pending',
            payload               JSONB       NOT NULL,
            visible_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            attempt_count         INT         NOT NULL DEFAULT 0,
            lease_timeout_seconds INT         NOT NULL DEFAULT 60 CHECK (lease_timeout_seconds > 0),
            lease_id              UUID NULL,
            leased_by             TEXT NULL,
            created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX idx_jobs_visible_status ON jobs (visible_at, status)
        WHERE status IN ('pending', 'in_progress');

        CREATE EXTENSION IF NOT EXISTS pgcrypto;
"""

def parse_rfc3339(s):
    return datetime.datetime.fromisoformat(s.replace('Z', '+00:00'))

@pytest.fixture(scope="module")
def postgres_container():
    with PostgresContainer("postgres:16-alpine") as postgres:
        yield postgres

@pytest.fixture
async def queue(postgres_container):
    host = postgres_container.get_container_host_ip()
    port = postgres_container.get_exposed_port(5432)
    user = postgres_container.username
    password = postgres_container.password
    dbname = postgres_container.dbname
    
    pg_uri = f"postgres://{user}:{password}@{host}:{port}/{dbname}"
    
    conn = await asyncpg.connect(pg_uri)
    try:
        await conn.execute("DROP TABLE IF EXISTS jobs")
        await conn.execute("DROP TYPE IF EXISTS job_status")
        await conn.execute(SCHEMA_SQL)
    finally:
        await conn.close()
        
    q = await PgQueue.connect(pg_uri)
    return q

@pytest.mark.asyncio
async def test_enqueue_idempotency(queue):
    key = "test-key-" + str(uuid.uuid4())
    job1 = await queue.enqueue(key, {"data": 1}, 10)
    assert job1 is not None
    assert job1.idempotency_key == key

    job2 = await queue.enqueue(key, {"data": 2}, 10)
    assert job2 is None

@pytest.mark.asyncio
async def test_dequeue_and_ack(queue):
    key = "k1-" + str(uuid.uuid4())
    await queue.enqueue(key, 1, 10)

    jobs = await queue.dequeue("worker1", 1, 3)
    assert len(jobs) == 1
    job = jobs[0]
    lease = job.lease_key()
    assert lease is not None

    acked = await queue.ack(lease)
    assert acked is not None
    assert acked.status == JobStatus.Done

    again = await queue.ack(lease)
    assert again is None

@pytest.mark.asyncio
async def test_nack_and_retry(queue):
    key = "k1-" + str(uuid.uuid4())
    await queue.enqueue(key, 1, 10)

    jobs = await queue.dequeue("worker1", 1, 3)
    lease = jobs[0].lease_key()
    assert lease is not None

    nacked = await queue.nack(lease, 3)
    assert nacked is not None
    assert nacked.status == JobStatus.Pending
    assert nacked.attempt_count == 1

    jobs2 = await queue.dequeue("worker2", 1, 3)
    assert len(jobs2) == 1
    assert jobs2[0].attempt_count == 2

@pytest.mark.asyncio
async def test_max_attempts(queue):
    key = "k1-" + str(uuid.uuid4())
    await queue.enqueue(key, 1, 10)

    # Attempt 1
    jobs = await queue.dequeue("w1", 1, 1)
    lease = jobs[0].lease_key()
    assert lease is not None

    # Nack with max_attempts = 1
    nacked = await queue.nack(lease, 1)
    assert nacked is not None
    assert nacked.status == JobStatus.Failed

@pytest.mark.asyncio
async def test_touch_lease(queue):
    key = "k1-" + str(uuid.uuid4())
    await queue.enqueue(key, 1, 10)
    jobs = await queue.dequeue("w1", 1, 3)
    lease = jobs[0].lease_key()
    assert lease is not None

    touched = await queue.touch(lease, 30)
    assert touched is not None
    
    visible_at_orig = parse_rfc3339(jobs[0].visible_at)
    visible_at_touched = parse_rfc3339(touched.visible_at)
    assert visible_at_touched > visible_at_orig

@pytest.mark.asyncio
async def test_nack_with_delay(queue):
    key = "k1-" + str(uuid.uuid4())
    await queue.enqueue(key, 1, 10)
    jobs = await queue.dequeue("w1", 1, 3)
    lease = jobs[0].lease_key()
    assert lease is not None

    # Nack with a one-hour delay (3600 seconds)
    nacked = await queue.nack(lease, 3, delay_seconds=3600.0)
    assert nacked is not None
    
    visible_at = parse_rfc3339(nacked.visible_at)
    now = datetime.datetime.now(datetime.timezone.utc)
    assert visible_at > now + datetime.timedelta(seconds=3500)

    # Should not be able to dequeue immediately
    jobs2 = await queue.dequeue("w2", 1, 3)
    assert len(jobs2) == 0

@pytest.mark.asyncio
async def test_ack_batch(queue):
    k1 = "k1-" + str(uuid.uuid4())
    k2 = "k2-" + str(uuid.uuid4())
    await queue.enqueue(k1, 1, 10)
    await queue.enqueue(k2, 2, 10)

    jobs = await queue.dequeue("w1", 10, 3)
    assert len(jobs) == 2

    leases = [j.lease_key() for j in jobs]
    acked = await queue.ack_batch(leases)
    assert len(acked) == 2
    assert all(j.status == JobStatus.Done for j in acked)
